---

version: "3.7"

services:
  exporter:
    build: .
    ports:
      - "9105:9105"
    environment:
      MYSQL_CONNECTION_STRING: "root:mysql@server-1:3306"
    restart: always

networks:
  default:
    external:
      name: monitor-net
